name: Daily CI

on:
  schedule:
    - cron: '23 14 * * 1-5'

jobs:
  get-date:
    runs-on: ubuntu-latest
    steps:
      - name: Add date to github output env
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

  test:
    needs: get-date
    uses: arup-group/actions-city-modelling-lab/.github/workflows/python-install-lint-test.yml@v1.1.0
    with:
      os: ubuntu-latest
      py3version: "12"
      {%- if cookiecutter.create_jupyter_notebook_directory|lower == "y" %}
      notebook_kernel: {{ cookiecutter.repository_name }}
      {%- endif %}
      pytest_args: '--no-cov'  # ignore coverage
      cache_env: false
      lint: false
      env_name: daily-ci

  slack-notify-ci:
    needs: test
    if: always()
    uses: arup-group/actions-city-modelling-lab/.github/workflows/slack-notify.yml@v1.1.0
    secrets:
      SLACK_WEBHOOK: {% raw %}${{ secrets.SLACK_WEBHOOK }}{% endraw %}
    with:
      result: {% raw %}${{ needs.test.result }}{% endraw %}
      channel: {{ cookiecutter.repository_name }}-feed
      message: Daily CI action
