name: Development docs CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
    paths-ignore:
      - tests/**
      - ".github/**/*"
      - "!.github/workflows/docs.yml"


jobs:
  docs-test:
    if: github.ref != 'refs/heads/main'
    uses: arup-group/actions-city-modelling-lab/.github/workflows/docs-deploy.yml@main
    with:
      deploy_type: test
      {%- if cookiecutter.create_jupyter_notebook_directory|lower == "y" %}
      notebook_kernel: {{ cookiecutter.repository_name }}
      {%- endif %}

  docs-update-latest:
    permissions:
      contents: write
    if: github.ref == 'refs/heads/main'
    uses: arup-group/actions-city-modelling-lab/.github/workflows/docs-deploy.yml@main
    with:
      deploy_type: update_latest
      {%- if cookiecutter.create_jupyter_notebook_directory|lower == "y" %}
      notebook_kernel: {{ cookiecutter.repository_name }}
      {%- endif %}

  docs-accessibility:
    needs: [docs-test]
    if: always() && needs.docs-test.result == 'success' && github.event_name == 'pull_request'
    permissions:
      contents: read
      pull-requests: write
    uses: arup-group/actions-city-modelling-lab/.github/workflows/docs-a11y.yml@add-docs-a11y-checker
    with:
      upload_report: true
      allow_pr_comment: true
      {%- if cookiecutter.create_jupyter_notebook_directory|lower == "y" %}
      notebook_kernel: {{ cookiecutter.repository_name }}
      {%- endif %}
