name: Pull Request CI

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md
      - CHANGELOG.md
      - LICENSE
      - CONTRIBUTING.md
      - docs/**
      - mkdocs.yml
      - ".github/**/*"
      - "!.github/workflows/pr-ci.yml"

jobs:
  {%- if cookiecutter.open_source_license == 'Not open source' %}
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pre-commit/action@v3.0.1
  {%- endif %}

  test:
    {%- if cookiecutter.open_source_license == 'Not open source' %}
    needs: lint
    {%- endif %}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        py3version: ["10", "12"]
      fail-fast: false
    uses: arup-group/actions-city-modelling-lab/.github/workflows/python-install-lint-test.yml@main
    with:
      os: {% raw %}${{ matrix.os }}{% endraw %}
      py3version: {% raw %}${{ matrix.py3version }}{% endraw %}
      {%- if cookiecutter.create_jupyter_notebook_directory|lower == "y" %}
      notebook_kernel: {{ cookiecutter.repository_name }}
      {%- endif %}
      lint: false
      pytest_args: '--no-cov'  # ignore coverage
      upload_to_codecov: false

  test-coverage:
    {%- if cookiecutter.open_source_license == 'Not open source' %}
    needs: lint
    {%- endif %}
    uses: arup-group/actions-city-modelling-lab/.github/workflows/python-install-lint-test.yml@main
    with:
      os: ubuntu-latest
      py3version: "12"
      {%- if cookiecutter.create_jupyter_notebook_directory|lower == "y" %}
      notebook_kernel: {{ cookiecutter.repository_name }}
      {%- endif %}
      lint: false
      pytest_args: 'tests/'  # ignore example notebooks
      {%- if cookiecutter.open_source_license != 'Not open source' %}
      upload_to_codecov: true
      {% else %}
      upload_to_codecov: false
      {%- endif %}

  memory-profile:
    uses: arup-group/actions-city-modelling-lab/.github/workflows/python-memory-profile.yml@main
    with:
      py3version: "12"
      upload_flamegraph: true

  cruft-check:
    uses: arup-group/actions-city-modelling-lab/.github/workflows/template-check.yml@main
