name: Publish stable docs

on:
  release:
    types: [released]

jobs:
  docs-stable:
    permissions:
      contents: write
    uses: arup-group/actions-city-modelling-lab/.github/workflows/docs-deploy.yml@main
    with:
      deploy_type: update_stable